<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_T</name>
   <tag></tag>
   <elementGuidId>77361cba-0226-49c3-90be-b893e00c1e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.e-9541-text.encore-text-body-small-bold.LKfKy7bXKmlkMEANVJMS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global-nav-bar']/div[3]/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;user-widget-link&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>689621d5-d14e-41ba-8874-d82ce65b2ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-9541-text encore-text-body-small-bold LKfKy7bXKmlkMEANVJMS</value>
      <webElementGuid>bd3dac4a-3753-4408-ad4b-d4501c3641e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8a31362-4fa7-4418-bc2b-48d61a4ced7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>username-first-letter</value>
      <webElementGuid>f097e14d-0066-4eff-8e45-fcc53733c784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>ebad9ecc-23e4-4c3d-b22b-f4cb17e7a911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-nav-bar&quot;)/div[@class=&quot;VUXMMFKWudUWE1kIXZoS rwdnt1SmeRC_lhLVfIzg&quot;]/button[@class=&quot;Button-sc-1dqy6lx-0 eA-Dwob encore-text-body-medium-bold e-9541-overflow-wrap-anywhere KAq2kDjXj2VS4eXrFL4i&quot;]/span[@class=&quot;e-9541-text encore-text-body-small-bold LKfKy7bXKmlkMEANVJMS&quot;]</value>
      <webElementGuid>ebb32fb8-48b0-40a8-a974-1fffe31313b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-nav-bar']/div[3]/button[2]/span</value>
      <webElementGuid>4e341b8c-86bb-4585-b9e3-99ce2c2320b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Install App'])[1]/following::span[1]</value>
      <webElementGuid>66991f15-690e-4d3f-aa7f-8b5279d3241e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore Premium'])[1]/following::span[3]</value>
      <webElementGuid>dcaa845b-001f-455d-8130-5946d6338ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lsa Faker'])[1]/preceding::span[2]</value>
      <webElementGuid>cbd3fc12-e877-417e-b19d-95d7353af786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='T']/parent::*</value>
      <webElementGuid>452c2062-9078-456e-a3c0-c806547569f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>e3521695-5779-48f5-9c18-a4d226ff3f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'T' or . = 'T')]</value>
      <webElementGuid>38ca917e-05df-45fc-b51f-a2f42f7c4b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
