<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_T_RowButton-sc-xxkq4e-0 fVLjWA</name>
   <tag></tag>
   <elementGuidId>3b821ee1-85c0-473d-adef-d58c8a93a8e9</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Desktop_LeftSidebar_Id&quot;)/nav[@class=&quot;lYpiKR_qEjl1jGGyEvsA&quot;]/div[@class=&quot;lHJd4oSttKLxkxuoZ0Lr wM72343CksOCaL3bZvKK&quot;]/div[@class=&quot;hgJel0bLlS_1Uf0EIfSA YourLibraryX sikBfynL1Y6I25nVpbAg&quot;]/div[@class=&quot;WxM1eb7qnneSkMiT4dvw ZjfaJlGQZ42nCWjD3FDm&quot;]/div[2]/div[@class=&quot;_W_0W9Uld1vxrRfsgdQR sikBfynL1Y6I25nVpbAg&quot;]/div[1]/ul[1]/div[@class=&quot;JUa6JJNj7R_Y3i4P8YUX&quot;]/div[2]/li[@class=&quot;NxEINIJHGytq4gF1r2N1 or84FBarW2zQhXfB9VFb odS2IW9wfNVHhkhc0l_X O0AN8Ty_Cxd4iLwyKATB XNjgtSbyhshr7YQcVvry vSC5QuwmzUhqUNWdMTJ5&quot;]/div[1]/div[@class=&quot;Box__BoxComponent-sc-y4nds-0 gozVzj Box-sc-8t9c76-0 chaEYk fYWNdY4zhj4OX_T2Xtg6 ZZsPF3Sn4h7m0_5Clhk0&quot;]/div[@class=&quot;RowButton-sc-xxkq4e-0 fVLjWA&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.RowButton-sc-xxkq4e-0.fVLjWA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Desktop_LeftSidebar_Id']/nav/div/div/div[2]/div[2]/div/div/ul/div/div[2]/li/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Playlist • testing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8c5a7890-2aed-4f20-a400-31ef61b55876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d4666e4-8a8b-4779-9993-5e78de7dd3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5939a0c1-4590-46c1-8e46-0f7a1a5fd31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>listrow-title-spotify:playlist:0doMBDqEqTSLHRea3ujbf9 listrow-subtitle-spotify:playlist:0doMBDqEqTSLHRea3ujbf9</value>
      <webElementGuid>d96713b8-072b-4c64-ad89-2c60f6d71c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>onClickHintspotify:playlist:0doMBDqEqTSLHRea3ujbf9</value>
      <webElementGuid>e182719b-9b7e-4dd9-8b7b-9de5fe848f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d42a5e84-7608-4e34-b734-5bb932b6f841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RowButton-sc-xxkq4e-0 fVLjWA</value>
      <webElementGuid>85d05389-bbdd-42af-bb4b-c94f2f568a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desktop_LeftSidebar_Id&quot;)/nav[@class=&quot;lYpiKR_qEjl1jGGyEvsA&quot;]/div[@class=&quot;lHJd4oSttKLxkxuoZ0Lr wM72343CksOCaL3bZvKK&quot;]/div[@class=&quot;hgJel0bLlS_1Uf0EIfSA YourLibraryX sikBfynL1Y6I25nVpbAg&quot;]/div[@class=&quot;WxM1eb7qnneSkMiT4dvw ZjfaJlGQZ42nCWjD3FDm&quot;]/div[2]/div[@class=&quot;_W_0W9Uld1vxrRfsgdQR sikBfynL1Y6I25nVpbAg&quot;]/div[1]/ul[1]/div[@class=&quot;JUa6JJNj7R_Y3i4P8YUX&quot;]/div[2]/li[@class=&quot;NxEINIJHGytq4gF1r2N1 or84FBarW2zQhXfB9VFb odS2IW9wfNVHhkhc0l_X O0AN8Ty_Cxd4iLwyKATB XNjgtSbyhshr7YQcVvry vSC5QuwmzUhqUNWdMTJ5&quot;]/div[1]/div[@class=&quot;Box__BoxComponent-sc-y4nds-0 gozVzj Box-sc-8t9c76-0 chaEYk fYWNdY4zhj4OX_T2Xtg6 ZZsPF3Sn4h7m0_5Clhk0&quot;]/div[@class=&quot;RowButton-sc-xxkq4e-0 fVLjWA&quot;]</value>
      <webElementGuid>52f73083-39cf-4b91-b331-182f71925e8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Desktop_LeftSidebar_Id']/nav/div/div/div[2]/div[2]/div/div/ul/div/div[2]/li/div/div/div</value>
      <webElementGuid>0d7de535-f4d8-47ce-b70a-e021589f833c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div</value>
      <webElementGuid>c2903c2c-d8f8-46e9-bd6a-99bfdd6640da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
