<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What do you want to play_Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf</name>
   <tag></tag>
   <elementGuidId>dbad4578-62a2-4cb1-8d4f-13c851d0e8b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.Input-sc-1gbx9xe-0.jlbmaj.e-9541-baseline.e-9541-form-control.encore-text-body-medium.CVuGEUIxLkNKpMds8AFS.R69APjfNV0o9tAbfrWZf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;search-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9203707-c29c-4f0c-ba35-59c232d97f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf</value>
      <webElementGuid>088de0c5-a167-455f-981f-51ad66700797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>fdd05a87-efbf-4f65-a6e5-f6bd2f638a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>b8651c9e-fac3-43b0-863f-ad321f7e0f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>recent-searches-dropdown</value>
      <webElementGuid>b519fe5f-7c77-4304-b1d3-b6219b943229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>recent-searches-dropdown</value>
      <webElementGuid>4511f83d-bdf4-49c7-9a00-63e02a697ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5783496-a274-4d04-9d36-d18e6f88c608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>258ec22e-b705-45ca-9244-435cd85d839a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-top-bar-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4bf76938-06aa-418b-8475-abc267287c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>f1ba2501-16d0-42cf-9a7b-5d53eabb7c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f4e916d-0e2a-46ed-af4e-64a7fd218d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What do you want to play?</value>
      <webElementGuid>f4fc8473-405f-438e-8968-7898ad9da1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1f9ba065-243a-43bc-b9df-92f1b6a392b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-nav-bar&quot;)/div[@class=&quot;gj5VcIUC9oD2p4BsxzGE&quot;]/div[@class=&quot;lj0eGI6WEtfxFX7irC03&quot;]/div[@class=&quot;kOrgVj4dtioqHnXeX9Ui&quot;]/span[@class=&quot;fmZ0hU6ImbDQi5qGWLvF&quot;]/div[@class=&quot;_b3hhmbWtOY8_1M1mM1H&quot;]/form[@class=&quot;InputContainer-sc-a5ofs0-0 hRYcJy b7r2WRiu5f9Q99qmyreh&quot;]/div[@class=&quot;ODl7TwNawIfBwiZv1Czg&quot;]/input[@class=&quot;Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf&quot;]</value>
      <webElementGuid>7f0bc6ca-3eec-426a-a16f-6d30cedfd1c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>248a008e-9576-456b-9e2a-ec327dfa2cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-nav-bar']/div[2]/div/div/span/div/form/div[2]/input</value>
      <webElementGuid>0c7bd7a4-a3db-4af9-9283-02f49fde10d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f95bd3bf-8525-463c-a7b4-42e245448fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'What do you want to play?']</value>
      <webElementGuid>68ff4e8c-a4a2-4e31-a0dc-ae92b58ac8fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
