<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Let, , s find something for your playlist)_e-9541-text encore-text-body-small FeWwGSRANj36qpOBoxdx</name>
   <tag></tag>
   <elementGuidId>b61b96ee-7f74-4082-95da-f0211817c564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.e-9541-text.encore-text-body-small.FeWwGSRANj36qpOBoxdx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search for songs or episodes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79eb4fc2-247b-465c-a8e7-1a41fee5be7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-9541-text encore-text-body-small FeWwGSRANj36qpOBoxdx</value>
      <webElementGuid>6fc0b7ef-9cbf-47fa-8cab-a11020074580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a39094b-5b90-4fe7-8231-4af19b6213f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>45504f13-ab8d-4573-809a-f2838dc07e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>b859b45d-4315-4edc-a811-c149bd2a129f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14915c32-bb77-4360-b0c5-192d0f666452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>05dfc482-bd9c-4a5f-b1a3-f4578865c58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7769654f-ae8d-4c7a-b353-157d2ef49080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for songs or episodes</value>
      <webElementGuid>e623ec28-c820-4bd9-bc47-171dfd61894a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;Root global-nav centered-layout&quot;]/div[@class=&quot;ZQftYELq0aOsg6tPbVbV&quot;]/div[@class=&quot;jEMA2gVoLgPQqAFrPhFw&quot;]/div[@class=&quot;main-view-container&quot;]/div[@class=&quot;main-view-container__scroll-node main-view-container__scroll-node--offset-topbar ZjfaJlGQZ42nCWjD3FDm&quot;]/div[2]/div[@class=&quot;main-view-container__scroll-node-child&quot;]/main[@class=&quot;T0fKO6B7LQSCE_VaSM1P&quot;]/section[1]/div[@class=&quot;rezqw3Q4OEPB1m4rmwfw&quot;]/div[@class=&quot;NxEINIJHGytq4gF1r2N1 or84FBarW2zQhXfB9VFb odS2IW9wfNVHhkhc0l_X XNjgtSbyhshr7YQcVvry O0AN8Ty_Cxd4iLwyKATB&quot;]/div[@class=&quot;contentSpacing&quot;]/section[@class=&quot;Ykd_JWqkR9gSLHISDBwP&quot;]/div[@class=&quot;g9xHCCSXDR8S5NvTbfwL&quot;]/div[@class=&quot;YAYCVnYpPvmYV4JyTmn5&quot;]/input[@class=&quot;e-9541-text encore-text-body-small FeWwGSRANj36qpOBoxdx&quot;]</value>
      <webElementGuid>f73e6621-e62b-4b83-acab-d92f238299e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>4dfc34f1-9fb5-47d8-adc5-cabde1b16f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div[4]/div/div[2]/div[2]/div/main/section/div[2]/div[3]/div/section/div/div/input</value>
      <webElementGuid>9bed8845-9e6f-45b3-b28e-68c5e3974b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>726de17e-0ea4-48b7-bdbb-eb07059b965c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search for songs or episodes']</value>
      <webElementGuid>724503cd-9a98-4ea3-b1c9-0c1d0efe3585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
