<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf</name>
   <tag></tag>
   <elementGuidId>4703a361-8bab-4225-996c-4ecfb79be03b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.Input-sc-1gbx9xe-0.jlbmaj.e-9541-baseline.e-9541-form-control.encore-text-body-medium.CVuGEUIxLkNKpMds8AFS.R69APjfNV0o9tAbfrWZf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;search-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c01930c2-a89b-4086-9d32-58072d3d0aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf</value>
      <webElementGuid>ffe18f77-3977-4bb8-b2af-e63e318db36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>ab859c4f-45fb-4601-b1bf-76fdb8dfe178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c8aedca2-d9db-4c63-a2c9-cddcb2485a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>recent-searches-dropdown</value>
      <webElementGuid>910329bf-3c29-4dc1-9b51-5f42e465fa4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>recent-searches-dropdown</value>
      <webElementGuid>657536a1-4b49-4c82-9c75-4e215d8cae84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4777aa2b-be67-4fb8-9b01-0be808e55290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>709fc4a0-d393-4395-a584-460b6042291d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-top-bar-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>afa70b2c-db98-4a1a-85cf-595e37280f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ef60ed54-968c-4f71-b3f3-faeb6ecb9302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>331f0442-ddad-421b-86a6-cfe8469f7f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What do you want to play?</value>
      <webElementGuid>697060d2-6e6b-4c5e-b098-b644e93bb509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>020d0a87-fb24-4644-a50c-053d0ae1b058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-nav-bar&quot;)/div[@class=&quot;gj5VcIUC9oD2p4BsxzGE&quot;]/div[@class=&quot;lj0eGI6WEtfxFX7irC03&quot;]/div[@class=&quot;kOrgVj4dtioqHnXeX9Ui&quot;]/span[@class=&quot;fmZ0hU6ImbDQi5qGWLvF&quot;]/div[@class=&quot;_b3hhmbWtOY8_1M1mM1H&quot;]/form[@class=&quot;InputContainer-sc-a5ofs0-0 hRYcJy b7r2WRiu5f9Q99qmyreh&quot;]/div[@class=&quot;ODl7TwNawIfBwiZv1Czg&quot;]/input[@class=&quot;Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf&quot;]</value>
      <webElementGuid>9923e314-ded7-4a22-860d-abe357a79b93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>97e60ead-1fa5-4188-b413-d3c3e661849c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-nav-bar']/div[2]/div/div/span/div/form/div[2]/input</value>
      <webElementGuid>75303ad5-1cda-4995-9403-949ed85410c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e93e179c-1c0a-43bc-b2d6-297aedab9b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'What do you want to play?']</value>
      <webElementGuid>8b9cc653-7474-47f1-9fa1-c5ff60af78af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
