<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_An error occurred while retrieving sharing information. Please try again later_ytp-timed-markers-container</name>
   <tag></tag>
   <elementGuidId>43ee3f61-49d3-4ef0-b518-89b07ef0120c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ytp-timed-markers-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[28]/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ytp-timed-markers-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36b6cc6f-27a5-4e6e-a95e-f8143765c61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-timed-markers-container</value>
      <webElementGuid>5670d4da-b1c9-4c6b-ac3a-ce308d89bf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-chrome-bottom&quot;]/div[@class=&quot;ytp-progress-bar-container&quot;]/div[@class=&quot;ytp-progress-bar&quot;]/div[@class=&quot;ytp-timed-markers-container&quot;]</value>
      <webElementGuid>97770484-5ce5-40a8-9783-a95d4e690c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[28]/div/div[2]/div[2]</value>
      <webElementGuid>453cf226-e0ff-4f14-aac2-ecd4ca459f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div[2]/div[2]</value>
      <webElementGuid>64832649-44b0-4918-97e7-65a5d132539c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
