<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to playlist</name>
   <tag></tag>
   <elementGuidId>4e665f2f-3787-41d9-9cd6-7b510ffc60a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mWj8N7D_OlsbDgtQx5GW</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='context-menu']/ul/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Add to playlist&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f9eacc7-791e-407c-ada4-aa079eae0711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mWj8N7D_OlsbDgtQx5GW</value>
      <webElementGuid>8a5deded-ee8f-4a64-bae8-bece51fc7480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>6abdb735-4a9e-43a7-b9d1-c3d62007dde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51a81c28-14b2-4dd1-bd96-ca3356c85091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>72ec5481-e6f4-4d74-8efd-73f7b9c30fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to playlist</value>
      <webElementGuid>d1eacd9e-6bb9-4ed2-9294-a7fcde75c54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;context-menu&quot;)/ul[@class=&quot;encore-dark-theme encore-layout-themes NbcaczStd8vD2rHWwaKv&quot;]/li[@class=&quot;rQ6LXqVlEOGZdGIG0LgP&quot;]/button[@class=&quot;mWj8N7D_OlsbDgtQx5GW&quot;]</value>
      <webElementGuid>f1813c79-08cc-4ee3-8d32-703bd8c8dd20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='context-menu']/ul/li/button</value>
      <webElementGuid>6df3aa1e-6d3d-44e1-b081-b67a3a5fa58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[1]</value>
      <webElementGuid>b939033f-40fe-4b44-9f0c-f15002b166cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New playlist'])[1]/preceding::button[2]</value>
      <webElementGuid>eccd2c87-6785-4f17-9e96-f10b733d6044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>b3fd71d9-ea32-4b96-bb4d-89da5a5da810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add to playlist' or . = 'Add to playlist')]</value>
      <webElementGuid>0322bdaa-7439-44a2-832c-176ce06495ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
