<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Recents_RowButton-sc-xxkq4e-0 fVLjWA</name>
   <tag></tag>
   <elementGuidId>f3c1c3e3-fe08-484d-bbf3-7bb9cc02d25f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.RowButton-sc-xxkq4e-0.fVLjWA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Desktop_LeftSidebar_Id']/nav/div/div/div[2]/div[2]/div/div[2]/ul/div/div[2]/li/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Playlist • testing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2cf4823-9849-4838-95a0-09625a4180e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2c56c50-d00e-4ee5-ad50-bf007b69a7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5cea5500-727d-4ca6-ac16-c9771877efd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>listrow-title-spotify:playlist:55tEeApdRPVTwXzPBx8fwa listrow-subtitle-spotify:playlist:55tEeApdRPVTwXzPBx8fwa</value>
      <webElementGuid>7876b6b4-7f84-4b79-99d2-6e3fad726fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>onClickHintspotify:playlist:55tEeApdRPVTwXzPBx8fwa</value>
      <webElementGuid>a40f560e-030a-4d4d-a21c-02f308a81606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c6fbe0be-98ed-4437-b7d6-5c9e1c315212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RowButton-sc-xxkq4e-0 fVLjWA</value>
      <webElementGuid>712d9da0-4cc1-4bcf-82cd-e35dc2964d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desktop_LeftSidebar_Id&quot;)/nav[@class=&quot;lYpiKR_qEjl1jGGyEvsA&quot;]/div[@class=&quot;lHJd4oSttKLxkxuoZ0Lr wM72343CksOCaL3bZvKK&quot;]/div[@class=&quot;hgJel0bLlS_1Uf0EIfSA YourLibraryX&quot;]/div[@class=&quot;WxM1eb7qnneSkMiT4dvw ZjfaJlGQZ42nCWjD3FDm&quot;]/div[2]/div[@class=&quot;_W_0W9Uld1vxrRfsgdQR&quot;]/div[2]/ul[1]/div[@class=&quot;JUa6JJNj7R_Y3i4P8YUX&quot;]/div[2]/li[@class=&quot;NxEINIJHGytq4gF1r2N1 or84FBarW2zQhXfB9VFb odS2IW9wfNVHhkhc0l_X O0AN8Ty_Cxd4iLwyKATB XNjgtSbyhshr7YQcVvry vSC5QuwmzUhqUNWdMTJ5&quot;]/div[@class=&quot;Box__BoxComponent-sc-y4nds-0 gozVzj Box-sc-8t9c76-0 chaEYk fYWNdY4zhj4OX_T2Xtg6&quot;]/div[@class=&quot;RowButton-sc-xxkq4e-0 fVLjWA&quot;]</value>
      <webElementGuid>7dbd16ef-54b6-457f-9308-2799e24aeaba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Desktop_LeftSidebar_Id']/nav/div/div/div[2]/div[2]/div/div[2]/ul/div/div[2]/li/div/div</value>
      <webElementGuid>e2345b83-2c58-4faa-9d51-44f741a99712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>4d95d759-1117-4b05-9ff0-de1c995f3120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
