<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What do you want to play_Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf</name>
   <tag></tag>
   <elementGuidId>c2cf319b-bd29-4c8a-a53b-cddd67d641a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.Input-sc-1gbx9xe-0.jlbmaj.e-9541-baseline.e-9541-form-control.encore-text-body-medium.CVuGEUIxLkNKpMds8AFS.R69APjfNV0o9tAbfrWZf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;search-input&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07c16d9b-d0cc-41f6-9f10-c9511ac11269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf</value>
      <webElementGuid>16732fad-25a8-4779-96ea-ef73e0915a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>19704fbf-7d60-4ff9-a9f4-33a7c1548a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>27aaeb14-f060-4b4d-8c2f-55a0c88cf7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>recent-searches-dropdown</value>
      <webElementGuid>a4138892-6d89-4397-97cc-64c33116a629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>recent-searches-dropdown</value>
      <webElementGuid>1f541341-1929-4b7f-a53d-e199354bc4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d853e29-2f8c-4fa1-9fb2-086688d39a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-input</value>
      <webElementGuid>9cf38f2a-ce84-4f3b-a7d4-6de3fff85b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-top-bar-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fe34d4c3-c304-4483-a21b-320d778ad2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d3a44ff4-bdac-425f-a96e-ecd0dc73d53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0030da1c-1c65-4d98-b7d4-e9afacb167d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What do you want to play?</value>
      <webElementGuid>c30bf966-b699-4161-88a7-96312d32a92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9aa7f858-77eb-486d-b017-ba0aa0f66a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-nav-bar&quot;)/div[@class=&quot;gj5VcIUC9oD2p4BsxzGE&quot;]/div[@class=&quot;lj0eGI6WEtfxFX7irC03&quot;]/div[@class=&quot;kOrgVj4dtioqHnXeX9Ui&quot;]/span[@class=&quot;fmZ0hU6ImbDQi5qGWLvF&quot;]/div[@class=&quot;_b3hhmbWtOY8_1M1mM1H&quot;]/form[@class=&quot;InputContainer-sc-a5ofs0-0 hRYcJy b7r2WRiu5f9Q99qmyreh&quot;]/div[@class=&quot;ODl7TwNawIfBwiZv1Czg&quot;]/input[@class=&quot;Input-sc-1gbx9xe-0 jlbmaj e-9541-baseline e-9541-form-control encore-text-body-medium CVuGEUIxLkNKpMds8AFS R69APjfNV0o9tAbfrWZf&quot;]</value>
      <webElementGuid>d249d455-cd75-4b4a-9386-4ae33a020fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>31136cac-119b-4ecf-b327-76a82dba2545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-nav-bar']/div[2]/div/div/span/div/form/div[2]/input</value>
      <webElementGuid>538e9bf4-d8a0-498a-b81b-da7442075011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7643cf21-b1e1-42d1-9dfe-026611258e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'What do you want to play?']</value>
      <webElementGuid>00a2b058-d3ad-4a2f-9eb6-25d2b850649a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
