<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_T_RowButton-sc-xxkq4e-0 fVLjWA</name>
   <tag></tag>
   <elementGuidId>996ed041-88f7-4399-b822-4e5225534de7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.RowButton-sc-xxkq4e-0.fVLjWA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Desktop_LeftSidebar_Id']/nav/div/div/div[2]/div[2]/div/div/ul/div/div[2]/li/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Playlist • testing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52cc3b05-109c-4c7c-99ec-5f8d309565e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2f695df-4600-48a1-8abd-02d2ab491a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c976ec68-cbd2-4c10-ae55-3e2dc7c12a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>listrow-title-spotify:playlist:0doMBDqEqTSLHRea3ujbf9 listrow-subtitle-spotify:playlist:0doMBDqEqTSLHRea3ujbf9</value>
      <webElementGuid>b7a2e97e-177e-4a17-a366-82431f7e492c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>onClickHintspotify:playlist:0doMBDqEqTSLHRea3ujbf9</value>
      <webElementGuid>921e6c52-3a4e-44e0-8522-03c8167d6ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>85ea553f-970b-497b-b628-8aeee98db139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RowButton-sc-xxkq4e-0 fVLjWA</value>
      <webElementGuid>bb937652-264c-4bf5-aaeb-cdb3cd730b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desktop_LeftSidebar_Id&quot;)/nav[@class=&quot;lYpiKR_qEjl1jGGyEvsA&quot;]/div[@class=&quot;lHJd4oSttKLxkxuoZ0Lr wM72343CksOCaL3bZvKK&quot;]/div[@class=&quot;hgJel0bLlS_1Uf0EIfSA YourLibraryX sikBfynL1Y6I25nVpbAg&quot;]/div[@class=&quot;WxM1eb7qnneSkMiT4dvw ZjfaJlGQZ42nCWjD3FDm&quot;]/div[2]/div[@class=&quot;_W_0W9Uld1vxrRfsgdQR sikBfynL1Y6I25nVpbAg&quot;]/div[1]/ul[1]/div[@class=&quot;JUa6JJNj7R_Y3i4P8YUX&quot;]/div[2]/li[@class=&quot;NxEINIJHGytq4gF1r2N1 or84FBarW2zQhXfB9VFb odS2IW9wfNVHhkhc0l_X O0AN8Ty_Cxd4iLwyKATB XNjgtSbyhshr7YQcVvry vSC5QuwmzUhqUNWdMTJ5&quot;]/div[1]/div[@class=&quot;Box__BoxComponent-sc-y4nds-0 gozVzj Box-sc-8t9c76-0 chaEYk fYWNdY4zhj4OX_T2Xtg6 ZZsPF3Sn4h7m0_5Clhk0&quot;]/div[@class=&quot;RowButton-sc-xxkq4e-0 fVLjWA&quot;]</value>
      <webElementGuid>70b77ec2-b7d8-4c1a-b186-cf7df7c8b491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Desktop_LeftSidebar_Id']/nav/div/div/div[2]/div[2]/div/div/ul/div/div[2]/li/div/div/div</value>
      <webElementGuid>eaab59fa-6c92-4ff5-afec-eae98c3ce2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div</value>
      <webElementGuid>10c7f7fd-daa6-4b7b-8f12-e0b4ac0a07e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
