<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to playlist</name>
   <tag></tag>
   <elementGuidId>5b8f6fc5-df5a-48a0-880e-47765b701563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mWj8N7D_OlsbDgtQx5GW</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='context-menu']/ul/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Add to playlist&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af5548fc-4bff-417e-b924-03d66aaae6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mWj8N7D_OlsbDgtQx5GW</value>
      <webElementGuid>299d44f8-8027-49b6-83b7-9d66f0e22a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>da687978-df90-4e55-8079-d01e4b42010a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67d9abce-da58-4c78-a88b-8aace310131d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>39613a15-b860-4f0d-a1e3-7306d78e965f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to playlist</value>
      <webElementGuid>27363854-5ef3-4f76-897e-881d06da77d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;context-menu&quot;)/ul[@class=&quot;encore-dark-theme encore-layout-themes NbcaczStd8vD2rHWwaKv&quot;]/li[@class=&quot;rQ6LXqVlEOGZdGIG0LgP&quot;]/button[@class=&quot;mWj8N7D_OlsbDgtQx5GW&quot;]</value>
      <webElementGuid>08d30426-7027-457e-adcd-33edd5d3770f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='context-menu']/ul/li/button</value>
      <webElementGuid>d3ad0840-60da-4901-9145-bad38559a3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[1]</value>
      <webElementGuid>276e0d5d-8329-444a-aefd-22c03650cba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New playlist'])[1]/preceding::button[2]</value>
      <webElementGuid>946fcc34-e658-4664-840c-63e226225705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>42afd370-2a33-4709-b98c-0d640c63f8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add to playlist' or . = 'Add to playlist')]</value>
      <webElementGuid>c880c5a4-1937-472f-9994-61f59356c358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
