<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Follow</name>
   <tag></tag>
   <elementGuidId>bfa36dff-08cc-4231-ad18-c11a9017e9df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.eSg4ntPU2KQLfpLGXAww > button.Button-sc-y0gtbx-0.cGnWXQ.encore-text-body-small-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div[4]/div/div[2]/div[2]/div/main/section/div/div[2]/div[2]/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Follow&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9985665a-752b-4f02-8b7f-bdb69ef87d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button-sc-y0gtbx-0 cGnWXQ encore-text-body-small-bold</value>
      <webElementGuid>48591942-8a1e-490a-a972-8329ff02d3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>buttonSecondary</value>
      <webElementGuid>296bc772-1b2e-4dc1-908a-0c5f54c871ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Follow</value>
      <webElementGuid>4f7b9b2a-a4bf-42da-b0a6-e51a413a93d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;Root global-nav centered-layout&quot;]/div[@class=&quot;ZQftYELq0aOsg6tPbVbV&quot;]/div[@class=&quot;jEMA2gVoLgPQqAFrPhFw&quot;]/div[@class=&quot;main-view-container&quot;]/div[@class=&quot;main-view-container__scroll-node main-view-container__scroll-node--offset-topbar ZjfaJlGQZ42nCWjD3FDm&quot;]/div[2]/div[@class=&quot;main-view-container__scroll-node-child&quot;]/main[@class=&quot;T0fKO6B7LQSCE_VaSM1P&quot;]/section[1]/div[1]/div[@class=&quot;EmeHQXR87mUskYK6xEde&quot;]/div[@class=&quot;ZjfaJlGQZ42nCWjD3FDm&quot;]/div[2]/div[@class=&quot;E4q8ogfdWtye7YgotBlN contentSpacing&quot;]/div[@class=&quot;eSg4ntPU2KQLfpLGXAww&quot;]/button[@class=&quot;Button-sc-y0gtbx-0 cGnWXQ encore-text-body-small-bold&quot;]</value>
      <webElementGuid>0da3c4a8-f0c7-4ade-a5d0-a7bac4cb213e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div[4]/div/div[2]/div[2]/div/main/section/div/div[2]/div[2]/div[2]/div/div/button</value>
      <webElementGuid>3b33f41f-bca5-45bb-a983-94de796b91cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verified Artist'])[1]/following::button[2]</value>
      <webElementGuid>f675f572-696e-493e-a119-6ae3b90b84d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change volume'])[1]/following::button[3]</value>
      <webElementGuid>d675af75-65a8-47a4-bd1a-72fbf82dafff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular'])[1]/preceding::button[2]</value>
      <webElementGuid>55619603-182a-4774-a358-07a6f4a077fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kan Nefsy'])[1]/preceding::button[3]</value>
      <webElementGuid>250ce3b8-8186-4662-8b57-99dea86fc68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Follow']/parent::*</value>
      <webElementGuid>a10edfa3-a9e7-4b7a-b7c0-1dc5b6cebabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/button</value>
      <webElementGuid>a98d5033-19f9-44b9-8603-d717bdb8a2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Follow' or . = 'Follow')]</value>
      <webElementGuid>3a73fd03-7721-4979-8d4c-acbca659d3a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
