<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign up</name>
   <tag></tag>
   <elementGuidId>33c1db68-176e-45c4-9d6a-14cbe0229bb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button-sc-1dqy6lx-0.eoOeNb.encore-text-body-small-bold.e-9541-overflow-wrap-anywhere.sibxBMlr_oxWTfBrEz2G</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global-nav-bar']/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;signup-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecfdf07a-d341-4120-bd76-c3e1847fde97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>signup-button</value>
      <webElementGuid>59f758ec-195b-45e9-86a4-d6527e44f02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button-sc-1dqy6lx-0 eoOeNb encore-text-body-small-bold e-9541-overflow-wrap-anywhere sibxBMlr_oxWTfBrEz2G</value>
      <webElementGuid>3927bc40-6aa9-4d10-bc98-ad9b4b09f327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>buttonTertiary</value>
      <webElementGuid>8a27ed82-c733-4871-9a0a-e243894c0f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>9217719f-fa2d-4b09-951d-758b8b83b1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-nav-bar&quot;)/div[@class=&quot;VUXMMFKWudUWE1kIXZoS rwdnt1SmeRC_lhLVfIzg&quot;]/div[@class=&quot;LKFFk88SIRC9QKKUWR5u&quot;]/button[@class=&quot;Button-sc-1dqy6lx-0 eoOeNb encore-text-body-small-bold e-9541-overflow-wrap-anywhere sibxBMlr_oxWTfBrEz2G&quot;]</value>
      <webElementGuid>23c0c0d4-a1c6-4358-b967-f1ce7b359962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-nav-bar']/div[3]/div[2]/button</value>
      <webElementGuid>57dbe6d0-a55a-4e11-853b-7464ab657805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Install App'])[1]/following::button[1]</value>
      <webElementGuid>59b83ec8-9bc3-40aa-b28a-7e642af14047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::button[1]</value>
      <webElementGuid>c2c4a53c-420b-4919-81d9-e9ca44ac390d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::button[1]</value>
      <webElementGuid>479d9f28-f107-4c8f-b2a1-fb070aa5f675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Library'])[1]/preceding::button[2]</value>
      <webElementGuid>7d5e74c8-8f2e-4ec3-9609-bfa7c97294cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up']/parent::*</value>
      <webElementGuid>4eea6a82-c1cd-4566-b2b1-a51eaeafc031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>19f79eec-d29d-47e9-8846-09cd185ff4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Sign up' or . = 'Sign up')]</value>
      <webElementGuid>8236b2f9-6d25-4039-9b7f-4fe742f73b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
