<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MonthJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember</name>
   <tag></tag>
   <elementGuidId>65db3b33-3ede-473b-b4de-e059f2daed43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;birthDateMonth&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bb1471de-0e8b-4c61-8e4c-ecfd8219c619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button-sc-nfsrja-0 Select-sc-3qvhho-0 fkGvUY jXMgLp encore-text-body-medium</value>
      <webElementGuid>389aec50-922d-454f-9698-20b9bc70b9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c841ad4e-0d17-42e3-bc37-b155f12c451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>95eee69e-27be-4c5d-944f-73f35fc5d3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>afd00735-87cc-4138-a96d-39f7203e1ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>bday-month</value>
      <webElementGuid>5ac8e75a-717e-4704-9028-293f6df35558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>birthDateMonth</value>
      <webElementGuid>4cad0a88-3f01-4639-b465-9b7f83c5453b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>birthdate-error-invalid</value>
      <webElementGuid>de7f6479-5421-4641-b942-ca6036600f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MonthJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember</value>
      <webElementGuid>aa5f3b88-81e0-4ca6-bbb0-6b048f7a8be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;month&quot;)</value>
      <webElementGuid>87fc9626-f9ef-4e46-a64e-3daa2eff83f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='month']</value>
      <webElementGuid>67fcfb65-ec5a-418e-a2eb-683094d979b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/section/div/form/div/div[2]/div/section/div[3]/div[2]/div[2]/div/div/select</value>
      <webElementGuid>248c534a-2d6b-4847-b7d5-852ec635ec72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::select[1]</value>
      <webElementGuid>f21a2a2b-5ee8-460f-ab9d-abfc039ece7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your date of birth.'])[1]/preceding::select[1]</value>
      <webElementGuid>d96251ed-33c3-49cd-abb1-cb81ce7504e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::select[1]</value>
      <webElementGuid>16af4abf-ac66-4ac8-aa39-619b53d62aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>952360fb-bdbf-481b-8992-51ee8580a994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'month' and @name = 'month' and (text() = 'MonthJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember' or . = 'MonthJanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember')]</value>
      <webElementGuid>5069e116-3d11-4992-8082-d7e3be5a1375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
