<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Next</name>
   <tag></tag>
   <elementGuidId>8d4c4cf3-bcc5-4fd8-b4b4-028c4ce83d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ButtonInner-sc-14ud5tc-0.hvvTXU.encore-bright-accent-set</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/section/div/form/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;submit&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d502ee9e-cbcb-41fe-956e-9fc911ce6a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ButtonInner-sc-14ud5tc-0 hvvTXU encore-bright-accent-set</value>
      <webElementGuid>68b76149-017c-4f9b-a73b-d51d29daca29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>7b74aac4-a1c2-4e34-8313-b447bac6ffc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/main[@class=&quot;sc-ifyrTC sXlyP&quot;]/section[@class=&quot;sc-dENhDJ pTLoS&quot;]/div[@class=&quot;sc-eEPDDI iuoPVV&quot;]/form[@class=&quot;sc-jHofgq hutrlF&quot;]/div[@class=&quot;sc-blcnQh gXAYSM&quot;]/button[@class=&quot;Button-sc-qlcn5g-0 VsdHm encore-text-body-medium-bold&quot;]/span[@class=&quot;ButtonInner-sc-14ud5tc-0 hvvTXU encore-bright-accent-set&quot;]</value>
      <webElementGuid>a132170e-6972-491e-96c9-630ee23f33d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/section/div/form/div[2]/button/span</value>
      <webElementGuid>88d3fc63-aebf-4c83-b747-5ed1c93a076a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prefer not to say'])[1]/following::span[1]</value>
      <webElementGuid>49e8475b-6f75-4c67-8358-71e23b6457ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Woman'])[1]/following::span[3]</value>
      <webElementGuid>a5b53a9d-3700-4567-bfb6-e1aa5204ed91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::span[2]</value>
      <webElementGuid>40325e1e-16be-46e7-bf71-551c7e628fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Service'])[1]/preceding::span[2]</value>
      <webElementGuid>2a3498b6-8923-45fe-b386-419f37bb8322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>f4cb3f44-af0a-4036-8cc9-204067798d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>902eb02d-a4fd-466e-a3bd-4de1f04877af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>c90cc2f9-44e3-4562-b368-4419d36907f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
