<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Install App_Svg-sc-ytk21e-0 dYnaPI e-9541-icon gPxvvwdrTY6FbTx3mvl1</name>
   <tag></tag>
   <elementGuidId>9854ceda-b567-49c5-9b90-dd8615f48806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.Svg-sc-ytk21e-0.dYnaPI.e-9541-icon.gPxvvwdrTY6FbTx3mvl1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Install App'])[1]/following::*[name()='svg'][3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Create&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>2f058c3d-9eb3-4615-9ac6-df19be7754e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-encore-id</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>5ba7d8c5-aa9c-4567-922a-f90f448d27d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4e3bc30-833d-4eaf-8afa-2115e136f947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>669caa25-ad6e-4caf-800b-ae446b0e8034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Svg-sc-ytk21e-0 dYnaPI e-9541-icon gPxvvwdrTY6FbTx3mvl1</value>
      <webElementGuid>e4062030-ebf3-459b-9429-0cbecbc03eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
      <webElementGuid>7ad149dc-e045-4acf-95f1-ecf0ddec2d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desktop_LeftSidebar_Id&quot;)/nav[@class=&quot;lYpiKR_qEjl1jGGyEvsA&quot;]/div[@class=&quot;lHJd4oSttKLxkxuoZ0Lr wM72343CksOCaL3bZvKK&quot;]/div[@class=&quot;hgJel0bLlS_1Uf0EIfSA YourLibraryX sikBfynL1Y6I25nVpbAg&quot;]/div[1]/header[@class=&quot;HjPqU_UW2egr14mRSom9 oZT8iKL42zhLAm_zE5F5&quot;]/div[@class=&quot;tAfozCQs48q1JYdphYXi iYP0xuQiJCgi7gx1jUPJ&quot;]/div[@class=&quot;BZh0f1vbOmruyp4_t9wy&quot;]/button[@class=&quot;AIlmv6h8bR5NY5R0VceT l5V7KOO1aHJ4R7jYTQuV&quot;]/svg[@class=&quot;Svg-sc-ytk21e-0 dYnaPI e-9541-icon gPxvvwdrTY6FbTx3mvl1&quot;]</value>
      <webElementGuid>dadb9e97-2fe4-4b23-8ef6-c450fe2403a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Install App'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>58771649-fc78-44cf-81b7-42ed36a52253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear recent searches'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>630c5630-a5bc-4799-9d36-efd8b72214ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resize main navigation'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>6ffcdd7c-5ea2-4336-93d4-1cdf7b42037b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-:--'])[1]/preceding::*[name()='svg'][6]</value>
      <webElementGuid>57288319-494c-4a21-ab90-1e2ac38eb751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
